language: c
sudo: reguired
os:
    - linux
    - osx
compiler:
    - gcc
    - clang
script:
  - ./configure
  - make
  - make check
  - test/wchar2test
before_script:
  - if [ "$(uname)" = "Linux" ]; then sudo apt-get update; sudo apt-get install -y autotools-dev autoconf check; fi
  - if [ "$(uname)" = "Darwin" ]; then brew update; brew install autoconf automake libtool check; fi
matrix:
    exclude:
        - os:       osx
          compiler: gcc
