.TH "mlicense" 3 "Sat Jul 14 2018" "libwchar2 0.0.3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlicense \- 'GNU glibc-2 manual License' 

.SH "Manual author and License"
.PP
\fBAuthor:\fP
.RS 4
(C) Bruno Haible haible@clisp.cons.org 
.PP
(C) 2014 Michael Kerrisk mtk.manpages@gmail.com 
.RE
.PP
\fBCopyright:\fP
.RS 4
GNU Public License version 2\&.
.RE
.PP
.SH "License details"
.PP
>This is free documentation; you can redistribute it and/or >modify it under the terms of the GNU General Public License as >published by the Free Software Foundation; either version 2 of >the License, or (at your option) any later version\&.
