.TH "wcsncasecmp" 3 "Sat Jul 14 2018" "libwchar2 0.0.3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wcsncasecmp \- 'wcsncasecmp manual' 

.SH "wcsncasecmp(3) - compare two fixed-size wide-character strings, ignoring case"
.PP
The \fBwcsncasecmp\fP() function is the wide-character equivalent of the \fBstrncasecmp\fP(3) function\&.
.PP
It compares the wide-character string pointed to by \fIs1\fP and the wide-character string pointed to by \fIs2\fP, but at most \fIn\fP wide characters from each string, ignoring case differences (\fBtowupper\fP(3), \fBtowlower\fP(3))\&.
.SH "Return Value"
.PP
The \fBwcsncasecmp\fP() function returns zero if the wide-character strings at \fIs1\fP and \fIs2\fP, truncated to at most length \fIn\fP, are equal except for case distinctions\&.
.PP
It returns a positive integer if truncated \fIs1\fP isgreater than truncated \fIs2\fP, ignoring case\&.
.PP
It returns a negative integer if truncated \fIs1\fP is smaller than truncated \fIs2\fP, ignoring case\&.
.PP
/*! # LibWchar2 library version
.PP
\fBVersion:\fP
.RS 4
libwchar2 0\&.0\&.3 
.RE
.PP
\fBDate:\fP
.RS 4
Sat Jul 14 2018 
.RE
.PP
\fBAuthor:\fP
.RS 4
(c) PS 2018-2018
.RE
.PP
# Manual author and License
.PP
\fBCopyright:\fP
.RS 4
GNU Public License version 2\&. \fBmanual License details\fP
.RE
.PP
*/  
