.TH "wcstoimax" 3 "Sat Jul 14 2018" "libwchar2 0.0.3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wcstoimax \- 'wcstoimax manual' 

.SH "wcstoimax(3) - convert wide-character string to integer"
.PP
These functions are just like \fBwcstol\fP(3) and \fBwcstoul\fP(3), except that they return a value of type \fIintmax_t\fP and \fIuintmax_t\fP, respectively\&.
.PP
/*! # LibWchar2 library version
.PP
\fBVersion:\fP
.RS 4
libwchar2 0\&.0\&.3 
.RE
.PP
\fBDate:\fP
.RS 4
Sat Jul 14 2018 
.RE
.PP
\fBAuthor:\fP
.RS 4
(c) PS 2018-2018
.RE
.PP
# Manual author and License
.PP
\fBCopyright:\fP
.RS 4
GNU Public License version 2\&. \fBmanual License details\fP
.RE
.PP
*/  
