.TH "wctob" 3 "Sat Jul 14 2018" "libwchar2 0.0.3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wctob \- 'wctob manual' 

.SH "wctob(3) - try to represent a wide character as a single byte"
.PP
The \fBwctob\fP() function tests whether the multibyte representation of the wide character \fIc\fP, starting in the initial state, consists of a single byte\&. If so, it is returned as an \fIunsigned char\fP\&.
.PP
Never use this function\&. It cannot help you in writing internationalized programs\&. Internationalized programs must never distinguish single-byte and multibyte characters\&.
.SH "Return Value"
.PP
The \fBwctob\fP() function returns the single-byte representation of \fIc\fP, if it exists, of \fBEOF\fP otherwise\&.
.SH "Notes"
.PP
The behavior of \fBwctob\fP() depends on the \fBLC_CTYPE\fP category of the current locale\&.
.PP
This function should never be used\&. Internationalized programs must never distinguish single-byte and multibyte characters\&.
.PP
Use either \fBwctomb\fP(3) or the thread-safe \fBwcrtomb\fP(3) instead\&.
.PP
/*! # LibWchar2 library version
.PP
\fBVersion:\fP
.RS 4
libwchar2 0\&.0\&.3 
.RE
.PP
\fBDate:\fP
.RS 4
Sat Jul 14 2018 
.RE
.PP
\fBAuthor:\fP
.RS 4
(c) PS 2018-2018
.RE
.PP
# Manual author and License
.PP
\fBCopyright:\fP
.RS 4
GNU Public License version 2\&. \fBmanual License details\fP
.RE
.PP
*/  
